name: segunda_aplicacion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
<<<<<<< HEAD
  day_night_switcher: ^0.2.0+1
  lottie: ^2.6.0
  concentric_transition: ^1.0.3
=======
>>>>>>> 9eb9b03 (Primer commit)
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
<<<<<<< HEAD
  assets:
    - assets/images/.
    - assets/animation/.

=======
>>>>>>> 9eb9b03 (Primer commit)
